version: 2
debug: true
workflows:
  version: 2
  regular_workflow:
    jobs:
      - small
      - small2
      - small3

jobs:
  small:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: sleep 60 && echo $CIRCLE_JOB
    resource_class: medium
  small2:
    docr:
      - image: circleci/ruby:2.4.1
    steps:
      - run: sleep 60 && echo $CIRCLE_JOB
    resource_class: medium
  small3:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: sleep 60 && echo $CIRCLE_JOB
    resource_class: medium
